config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'words#index'
  # resources :words, only: %i[index new create show edit update destory] # [ :index :new :create ]

  resources :words
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :words
    validates :name, presence: true 
    validates :name, inclusion: { in: LanguageList::COMMON_LANGUAGES.map(&:name) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :words
end

app/models/word.rb
class Word < ApplicationRecord
    belongs_to :language
    belongs_to :user
    validates :content, :language,  presence: true 

    paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  private
  
  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
    before_action :authenticate_user!, only: %i[new create edit update destroy] 
    before_action :set_word, only: %i[show edit update destroy]

    def index 
        @words = Word.page params[:page]
    end

    def new 
        @word = current_user.words.new
    end

    def create
      @word = Word.new(word_params)
      @word.user = current_user
      if @word.save
        redirect_to(words_path)
      else
        render :new
      end
    end

    def show; end

    def edit 
      authorize @word
    end

    def update
      authorize @word
      if @word.update(word_params)
        redirect_to(words_path(@word))
      else
        render :edit
      end
    end

    def destroy
      @word.destroy
      redirect_to(words_path)
    end

    private 
    
    def word_params
        params.require(:word).permit(:content, :language_id)
    end

    def set_word 
      @word = Word.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Myapp61
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render 'shared/navs'
      = render 'shared/messages'
      = yield
      

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} x
    %ul
      %li
        = value

app/views/shared/_navs.html.haml
.container-fluid
  .row
    .col-md-12
      %ul.nav
        %li.nav-item 
          = link_to('Home', root_path, class: 'nav-link')
        %li.nav-item
          = link_to('Create new word', new_word_path, class: 'nav-link')
        - if user_signed_in?
          %li.nav-item
            = link_to('Edit registration', edit_user_registration_path, class: 'nav-link')
        - else
          %li.nav-item
            = link_to('Register', new_user_registration_path, class: 'nav-link')
        - if user_signed_in?
          %li.nav-item
            = link_to('Logout', destroy_user_session_path, class: 'nav-link', method: :delete)
        - else 
          %li.nav-item
            = link_to('Login', new_user_session_path, class: 'nav-link') 
        -# %li.nav-item
        -#   %a.nav-link.disabled{:href => "#"} Messages
        -# %li.nav-item.dropdown.ml-md-auto
        -#   %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{"data-toggle" => "dropdown", :href => "http://example.com"} Dropdown link
        -#   .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdownMenuLink"}
        -#     %a.dropdown-item{:href => "#"} Action
        -#     %a.dropdown-item{:href => "#"} Another action
        -#     %a.dropdown-item{:href => "#"} Something else here
        -#     .dropdown-divider
        -#     %a.dropdown-item{:href => "#"} Separated link

app/views/words/_form.html.haml
= simple_form_for @word do |f|
  = f.input :content
  = f.association :language
  %br
  = f.button :submit, class: 'btn btn-primary'

app/views/words/edit.html.haml
%h1 New Word
= render 'form'

app/views/words/index.html.haml
%h2 Words view
%p
  You have
  = @words.count
  words in database!
%table.table
  %thead
    %tr
      %th
        \#
      %th
        Content
      %th
        Language 
      %th
        User 
      %th
        Actions
        %tbody
        - @words.each do |word|
          %tr.table-active
            %td
              = word.id
            %td
              = word.content
            %td
              = word.language&.name
            %td
              = word.user&.email
            %td
              = link_to('Show', word_path(word), class: 'btn btn-primary')
              //- if word.user != nil && word.user == current_user
              = link_to('Edit', edit_word_path(word), class: 'btn btn-primary')
              = link_to('Delete', word_path(word), class: 'btn btn-danger', method: :delete)
= paginate @words, theme: 'bootstrap-5', pagination_class: "pagination-sm"

app/views/words/new.html.haml
%h1 New Word
= render 'form'

app/views/words/show.html.haml
%h1 Word
%p
  = @word.content
%p
  = @word.language&.name